class FacebookVideo(object):
    
    # [FBProperty: length]
    def getLength(self):
        return self.videoLength
    
    # [FBProperty: place]
    def getPlace(self):
        return self.place
       
    # [FBProperty: source] 
    def getSource(self):
        return self.source
      
    # [FBProperty: title]  
    def getTitle(self):
        return self.title
        
    # [FBProperty: content_category]
    # BEAUTY_FASHION, BUSINESS, CARS_TRUCKS, COMEDY, CUTE_ANIMALS, ENTERTAINMENT, FAMILY, FOOD_HEALTH, HOME, LIFESTYLE, MUSIC, NEWS, POLITICS, SCIENCE, SPORTS, TECHNOLOGY, VIDEO_GAMING, OTHER
    def getContentCategory(self):
        return self.contentCategory
        
    # [FBProperty: universal_video_id]
    def getUniversalVideoId(self):
        return self.universalVideoId
        
    # [FBProperty: live_status]
    def getLiveStatus(self):
        return self.liveStatus
        
    # [FBProperty: created_time]
    def getCreatedTime(self):
        return self.createdTime
        
    # [FBProperty: description]
    def getDescription(self):
        return self.description
        
    # [FBProperty: id]
    def getId(self):
        return self.id
        
    # Edge Methods
    # [FBProperty: auto_generated_captions]
    def getAutoGeneratedCaptions(self):
        return self.autoGeneratedCaptions
        
    # [FBProperty: captions]
    def getCaptions(self):
        return self.captions
        
    # [FBProperty: comments]
    def getComments(self):
        return self.comments
        
    # [FBProperty: likes]
    def getLikes(self):
        return self.likes
        
    # [FBProperty: reactions]
    def getReactions(self):
        return self.reactions
        
    # [FBProperty: sponsor_tags]
    def getSponsorTags(self):
        return self.sponsorTags
        
    # [FBProperty: tags]
    def getTags(self):
        return self.tags
        
    # [FBProperty: tags]
    def getInsights(self):
        return self.tags
        
    # [FBProperty: video_insights]
    def getVideoInsights(self):
        return self.tags
        
    